import fs from 'node:fs';
import path from 'node:path';

// Load the near-duplicate redirect map (generated by
// scripts/ihatecbts_dedupe_sets_pass7.mjs). 301s the duplicate slug to the
// canonical one so SEO consolidates and visitors land on the single
// authoritative version of each Q&A set.
function loadDedupeRedirects() {
  const file = path.join(process.cwd(), 'scripts', 'dedupe_redirects.json');
  if (!fs.existsSync(file)) return [];
  try {
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    return (data.redirects || []).map(r => ({
      source: `/answers/${r.from}`,
      destination: `/answers/${r.to}`,
      permanent: true,
    }));
  } catch {
    return [];
  }
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  experimental: {
    serverComponentsExternalPackages: ['pdf-parse'],
  },
  async headers() {
    return [
      {
        source: '/api/ext/:path*',
        headers: [
          { key: 'Access-Control-Allow-Origin', value: '*' },
          { key: 'Access-Control-Allow-Methods', value: 'POST, OPTIONS' },
          { key: 'Access-Control-Allow-Headers', value: 'Content-Type' },
        ],
      },
      // SSG pages — cache aggressively at the edge + browser. Source data
      // only changes on deploy, so 1hr edge + 1day stale-while-revalidate
      // gives Render breathing room under concurrent load (the audit's
      // load agent flagged 8s p95 on /answers without this).
      {
        source: '/answers',
        headers: [
          { key: 'Cache-Control', value: 'public, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },
      {
        source: '/answers/:slug',
        headers: [
          { key: 'Cache-Control', value: 'public, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },
      {
        source: '/answers/topic/:slug',
        headers: [
          { key: 'Cache-Control', value: 'public, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },
      {
        source: '/answers/q/:slug',
        headers: [
          { key: 'Cache-Control', value: 'public, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },
      {
        source: '/sitemap.xml',
        headers: [
          { key: 'Cache-Control', value: 'public, s-maxage=3600, stale-while-revalidate=86400' },
        ],
      },
    ];
  },
  async redirects() {
    return loadDedupeRedirects();
  },
};

export default nextConfig;
